name: C++ CI/CD

# 添加权限配置
permissions:
  contents: write    # 这允许工作流创建releases
  issues: write     # 如果需要在release时创建issues
  pull-requests: write  # 如果需要在release时创建PR

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0   # 确保能获取所有的tag信息
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build
      run: |
        cd build
        make
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          build/minidb
          LICENSE
          README.md
        draft: false
        prerelease: false
        generate_release_notes: true
        
    - name: Upload artifacts
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: build/minidb